### ISSUE TITLE
[Edit] Save and Discard

### ISSUE THREAD

**Issue by mziyambi** [MetropolitanTransportationCommission/rtp-fullstack#100]
Right now I have these as buttons at the bottom of each card, but probably makes sense to have them more visible. Maybe the top of each card right justified and opposite the other buttons like the previous version? Or floating on the right side like where we were going to have the feedback button?

I also added a save button unique for each card/form which works ok. If you have a simpler way of switching the Update functions but using the same button that would be cool.

**Comment by mziyambi** [comment]
Also Prev/Next necessary again?

**Comment by gilbertfrausto** [comment]
commit 01a06828ac58db2a28a6b7419e71bddace9704d
