### ISSUE TITLE
[view projects] Implement pipe/ajax solution for Project Filter

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/rtp-fullstack#108]
See url: http://lorenzofox3.github.io/smart-table-website/ and review section for pipe/ajax plugin.

When choosing filter options the pagination is  not being reset correctly.

When you select next page, the filters are lost.

**Comment by mziyambi** [comment]
This is due to the side panel having a duplicate table id of displayedColection.

**Comment by mziyambi** [comment]
Try implementing  http://plnkr.co/edit/Kao9707ikzstbvqLFAcc?p=preview
