### ISSUE TITLE
[Bundling] Database Add tables/sp/views

### ISSUE THREAD

**Issue by mziyambi** [MetropolitanTransportationCommission/rtp-fullstack#34]
Add tables, stored procedures and views for viewing, inserting, deleting bundles.

**Comment by solofoo** [comment]
IN DEV:

CREATE TABLE [dbo].[Bundle_Set](
	[ID] [int] IDENTITY(1,1) primary key NOT NULL,
	[Bundle_Set_ID] [nvarchar](60) NULL,
	[Bundle_Set_Name] [nvarchar](255) NULL,
	[Owner] [nvarchar](255) NULL)

CREATE TABLE [dbo].[Bundle_Set_Bridge](
	[ID] [int] IDENTITY(1,1) primary key NOT NULL,
	[Bundle_Set_ID] [nvarchar](60) NULL,
	[Bundle_ID] [nvarchar](60) NULL)

CREATE TABLE [dbo].[Bundle](
	[ID] [int] IDENTITY(1,1) primary key NOT NULL,
	[Bundle_ID] [nvarchar](60) NULL,
	[Bundle_Name] [nvarchar](60) NULL,
	[Custom_ID] [nvarchar] (255) NULL)

CREATE TABLE [dbo].[Bundle_Project_Bridge](
	[ID] [int] IDENTITY(1,1) primary key NOT NULL,
	[Bundle_ID] [nvarchar](60) NULL,
	[Project_ID] [nvarchar](60) NULL)

**Did not add stored procedures.  Wait to talk to Kristen.

**Comment by solofoo** [comment]
@mziyambi @Keareys wondering if the Bundle_Set is basically the equivalent of a list?

**Comment by mziyambi** [comment]
Yeah, it is. But since we have lists already, i think it makes sense to drop bundle sets and just have bundles. You can then create a 'list' of bundled projects if you need to
