### ISSUE TITLE
Changes to Production DB for the next release

### ISSUE THREAD

**Issue by solofoo** [MetropolitanTransportationCommission/rtp-fullstack#37]

**Comment by Keareys** [comment]
Create Stored Procedures for Updating Mapping_Data tbl, and managing correspondence tables for All Policy Layers and Mapped Projects.  The procedure should be based in part on the following QRYs:

--Create Policy Overlay View that contains a union of all of the Policy Boundaries.  This will be used to select projects that intersect the policy features.
Create View dbo.PolicyOverlays as
select 'HOAs' as overlay, Shape, WKT_WGS84 From HOAs
Union All
select 'PDAs' as overlay, Shape, WKT_WGS84 From PDAs
Union All
select 'TPAs' as overlay, Shape, WKT_WGS84 From TPAs
Union All
select 'COCs' as overlay, Shape, WKT_WGS84 From COCs_2017

--Project Overlay for Performance Projects.  Finds all policy polygons that intersect a project shape.
create view dbo.PerformancePolicyOverlay as
SELECT       Distinct p.Project_ID, p.Performance_Name, p.Perf_ID, md.InPDA, md.InCOC, md.InHOA, md.InTPA, md.WKT_WGS84, md.Feature_Type, po.overlay, po.WKT_WGS84 as PolicyOverlay_WKT
FROM            PolicyOverlays po, Performance_Bundle AS p INNER JOIN
                         Mapping_Data AS md ON p.Project_ID = md.Project_ID
Where md.[SHAPE].STIntersects(po.Shape)=1 

--Create a Correspondence table for all projects that overlay a policy layer.  This table will be used to select the Policy Overlay features for display purposes in the application.
--HOAs
select ROW_NUMBER() OVER(ORDER BY GETDATE()) AS RecID, Project_ID, Overlay, PolicyOverlay_WKT 
into dbo.PerformanceProjects_HOAs
From dbo.PerformancePolicyOverlay where Overlay = 'HOAs'

--PDAs
select ROW_NUMBER() OVER(ORDER BY GETDATE()) AS RecID, Project_ID, Overlay, PolicyOverlay_WKT 
into dbo.PerformanceProjects_PDAs
From dbo.PerformancePolicyOverlay where Overlay = 'PDAs'

--COCs
select ROW_NUMBER() OVER(ORDER BY GETDATE()) AS RecID, Project_ID, Overlay, PolicyOverlay_WKT 
into dbo.PerformanceProjects_COCs
From dbo.PerformancePolicyOverlay where Overlay = 'COCs'

--TPAs
select  ROW_NUMBER() OVER(ORDER BY GETDATE()) AS RecID, Project_ID, Overlay, PolicyOverlay_WKT 
into dbo.PerformanceProjects_TPAs
From dbo.PerformancePolicyOverlay where Overlay = 'TPAs'

**Comment by solofoo** [comment]
SELECT        p.Project_ID, p.Performance_Name, p.Perf_ID, md.InPDA, md.InCOC, md.InHOA, md.InTPA, md.WKT_WGS84, md.Feature_Type, po.overlay, 
                         po.WKT_WGS84 AS PolicyOverlay_WKT
FROM            dbo.PolicyOverlays AS po CROSS JOIN
                         dbo.Performance_Bundle AS p INNER JOIN
                         dbo.Mapping_Data AS md ON p.Project_ID = md.Project_ID
WHERE        (md.SHAPE.STIntersects(po.Shape) = 1)

**Comment by solofoo** [comment]
[dbo].[sp_SyncToMappingData]  in dev/test/production db.  took out ref to production db in script
