### ISSUE TITLE
Changes to Production DB for the next release -MZ

### ISSUE THREAD

**Issue by solofoo** [MetropolitanTransportationCommission/rtp-fullstack#38]

**Comment by mziyambi** [comment]
Change Project_List_LU to Project_List_Bridge
Change Project_List to Project_List_LU

Add view -- dbo.ProjectList_Grid_VW

**Comment by mziyambi** [comment]
Add procedure: dbo.InsertIntoList
Add procedure: dbo.DeleteFromList

**Comment by solofoo** [comment]
Change Project_List_LU to List 
Add procedures (to keep in line with naming convention/try to establish one): 
[sp_InsertProjectList]
[sp_DeleteProjectList]

Please use these to update the bridge table.  I've updated the insertlist/deletelist to point to the List table.

**Comment by solofoo** [comment]
Update sp_DeleteProject so that if a proj is deleted, it is removed from the Project_List_Bridge

**Comment by solofoo** [comment]
Bundle_Project_Map_VW
Bundle_Project_VW

**Comment by solofoo** [comment]
sp_Insert_NewList
sp_DeleteList

**Comment by solofoo** [comment]
Project_Main_VW_Unchanged-removed [feature_type], [shape], [shape_nad83] fields from view in dev, replicate in production

**Comment by solofoo** [comment]
Added where sponsor status <> 'deleted' to all project/grid views, to project list grid vw, to two bundle vws.
