### ISSUE TITLE
Project Performance Grid View

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/rtp-fullstack#61]
Create a grid view that groups the following fields for the Performance Bundle:
Sponsor (Comma Separated List), County (Comma Separated List), Total Cost (Summarized).

Also include the Performance Title and performance ID.

**Comment by solofoo** [comment]
Created View in DEV db:
[rtp2017_dev].[dbo].[Performance_Bundle_Grid_VW]

I added Mapping_Status (max), so anything "Not Yet Mapped" will show if it exists, and then "Needs Confirmation", and then "Mapped".

**Comment by solofoo** [comment]
@mziyambi Let me know if we can roll this into tomorrow's release

**Comment by solofoo** [comment]
I have a couple other views that I would like to switch out on the db side
