### ISSUE TITLE
[UI] Rework Dashboard Interface using Tabbed Views

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/rtp-fullstack#72]
Use the following example as a starting point:
http://bootsnipp.com/snippets/featured/simple-vertical-tab

Sections should be as follows:
Projects
Messages
Admin

**Comment by gilbertfrausto** [comment]
commit 59d29cc361cc27e0587bb593386405f1bed36f94

**Comment by Keareys** [comment]
Fix spacing around the Dashboard items. White space should be equal around all the items in the section. Review alignment of all elements on all pages.  Elements should be aligned using a typical grid/box layout.  I'd like you to drop the white background on the dashboard or as another option, keep the white background but increase it's size so that it fills the bottom view.  I can answer any questions related to this change if you have any.

**Comment by gilbertfrausto** [comment]
Are you talking about the white background on the tabs? Because you requested that. I kept that off in previous dash mock ups.
White space and alignment? They are in a 100% column layout. All the panels have the same dimensions, made sure of that on Friday. With the exception of "who's online" which does need fixing

**Comment by Keareys** [comment]
Also, please check text alignment in the Dashboard pill buttons.  Text should be centered.

**Comment by Keareys** [comment]
When you look at the layout, does the spacing around the boxes look equal on your screen?  If needed, I can create an example of what I'd like it to look like.  But the real question is, does it look/appear correct on your screen?

**Comment by Keareys** [comment]
You  know what, screw it Gil, this does no longer matters to me. If you do not see a problem, than I won't see a problem.  I will just address these minor UI inconsistencies on my own at a later time.  Mike's questions regarding the spacing relates to the responsive design of the layout.  If you decrease the size of your browser, watch how the layout changes.  There are some odd behaviors as you move from large resolution to small.

1920 x 900 looks fine
1280 x 600 looks bad
1024 x 768 looks really bad
I will send you some screenshots as well if needed.  I am using the responsive view tools in firefox.

**Comment by Keareys** [comment]
Here are the top 10 US Browser sizes used according to google:
![top-10-us-screen-resolutions](https://cloud.githubusercontent.com/assets/6600484/12561219/ca141fc2-c353-11e5-9954-a9192bafddf1.jpg)

We should at least support the top 5.  Thoughts, suggestions?

**Comment by gilbertfrausto** [comment]
All you had to say is you had some responsive design issues.
As for the other issues. everything is center and same dimensions. Except for the white panel which you would like to discard anyways and the pill text is centered but left aligned. I can just revert the panels back and add the anchor back
![screen shot 2016-01-25 at 11 34 05 am](https://cloud.githubusercontent.com/assets/7200515/12562172/95eda2c2-c358-11e5-8ff6-db69009985e8.png)

**Comment by gilbertfrausto** [comment]
I'll be the first to left you know the issues you are seeing is because of the tabs. I would recommend.
-Removing the tabs
-Removing the white background
-Add 3 buttons to control a "tab like" view in the user nav
That would fix the responsive issue and keep everything similar to what you wanted

**Comment by Keareys** [comment]
I'd like to keep the Tabbed view.  Therefore, I will work on the Dashboard fixes going forward.  This issue will be switched to me.

**Comment by gilbertfrausto** [comment]
Any particular reason why? It's not helping the team if you are not discussing reasons for doing things a certain way. The jquery version had an open forum for discussion, that development cycle went a lot smoother. Maybe we should look at what was working and what wasn't. I think that would be very helpful
