### ISSUE TITLE
[UI] Rework Project Grid View Pages.  I will update/replace the project grid.  Incorporate the side banner tools.

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/rtp-fullstack#98]
Fix UI Layout for all Project Views.  Use the mock-up example that I provided earlier.  

The page title should be aligned at the top left of the Grid Views.  

Drop the drop shadow and underlined text.

Drop the white background.  

Make sure that the grid view fits within the space provided below the User Name Banner.

Comment:
The User Name Banner takes up a lot of page real estate and really does not serve a purpose for all pages except for the Dashboard.  Can we use that area for the Page View Titles Instead?  It may work better.  Thoughts suggestions??

**Comment by gilbertfrausto** [comment]
Name banner obliviously a bug, as projects views will look like the mock up you approved

**Comment by Keareys** [comment]
Grid view has been updated.  We still need to address the name banner bug.

**Comment by Keareys** [comment]
Completed
